environment:
  STRIPE_SECRET_KEY: ${STRIPE_SECRET_KEY}
  STRIPE_WEBHOOK_ENDPOINT_SECRET: ${STRIPE_WEBHOOK_ENDPOINT_SECRET}
  LOG_DESTINATIONS: ${LOG_DESTINATIONS}
packages:
  - name: payments
    actions:
    - name: stripe
  - name: webhooks
    actions:
    - name: stripe_webhook
      web: true